data_new
loop_
    _a
    _b
 1 2
 3 4
loop_
    _c
    _d
    _e
 1 2 3
 3 4 4
 'c' 'd' 'e'

Traceback (most recent call last):
  File "tests/shtests/build_cif_002.sh", line 26, in <module>
    datablock.add_loop( [ '_a', '_f' ], [[ 1, 1 ]] )
  File "/home/andrius/src/cod-tools/trunk/src/components/pycodcif/pycodcif.py", line 468, in add_loop
    raise KeyError( "data item '{}' already exists".format(key) )
KeyError: "data item '_a' already exists"
