scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_040.inp TEST_TYPE_CONTENTS_REFERENCED_ID_DIC: WARNING, content type of the '_invalid_type_contents_referenced_id.self_ref' data item could not be resolved due to a circular reference caused by the '_type.contents_referenced_id' attribute -- the default 'Text' content type will be used.
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_040.inp TEST_TYPE_CONTENTS_REFERENCED_ID_DIC: WARNING, definition of the '_invalid_type_contents_referenced_id.undefined_ref' data item references the '_item.exists_not' data item for its content type, but the referenced data item is not defined in the dictionary -- the default 'Text' content type will be used.
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_040.inp data_TEST_TYPE_CONTENTS_REFERENCED_ID_DIC save_invalid_type_contents_referenced_id.self_ref: WARNING, definition references itself using the '_type.contents_referenced_id' attribute.
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_040.inp data_TEST_TYPE_CONTENTS_REFERENCED_ID_DIC save_invalid_type_contents_referenced_id.undefined_ref: WARNING, attribute '_type.contents_referenced_id' references the '_item.exists_not' data item that is not defined in the given dictionary.
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_040.inp data_TEST_TYPE_CONTENTS_REFERENCED_ID_DIC save_invalid_type_contents_referenced_id.not_byreference: WARNING, data item contains the '_type.contents_referenced_id' attribute, but the '_type.contents' attribute value is not set to 'ByReference'.
scripts/cif_ddlm_dic_check: tests/cases/cif_ddlm_dic_check_040.inp data_TEST_TYPE_CONTENTS_REFERENCED_ID_DIC save_invalid_type_contents_referenced_id.no_type_contents: WARNING, data item contains the '_type.contents_referenced_id' attribute, but the '_type.contents' attribute value is not set to 'ByReference'.
