scripts/cif_printout_Python: tests/cases/cif_printout_Python_002.inp(1): ERROR, stray CIF values at the beginning of the input file.
